version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /bundle/vendor
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  worker:
    build: .
    command: bash -c "bundle exec shoryuken -R -C config/shoryuken.yml"
    volumes:
      - .:/app
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
volumes:
  bundle_path:
  db_data:
