default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'cinema_matcher_db' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres'} %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password'} %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'cinematcher_test'} %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'cinematcher_test'} %>


production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
